platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: 0d4aa7db017a10728ef402de8b4443d3c89e5b80

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: 192e15844a8868effc3e9868158a23d7708acead

- name: Ubuntu
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 3c82e3870bf72d0865e7af044d822babc3f581e6

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: eb502dec8ab1280b522fbd8da70cb68c0f1f576d

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: master
  commit: da64d6c38d9c2541702be7d60aa5de7c37836be7

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 3132855d1873ce065059e3647be58f6b608c3a1f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 53b61a46c27406623cdf7e727a2958aca98a1cda
