name: Code Format, Chinese Character and Header Check

on:
  pull_request:
    branches:
      - master
      - dev
      
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.cc'
      - '**/*.cxx'

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch full git history for diff comparison
        fetch-depth: 0
        
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-14
        sudo ln -sf /usr/bin/clang-format-14 /usr/bin/clang-format
        
    - name: Verify clang-format installation
      run: clang-format --version
      
    - name: Run code format, Chinese character and header check
      run: |
        python tools/check_format.py --base origin/${{ github.base_ref }} --verbose
        
    - name: Check failure instructions
      if: failure()
      run: |
        echo "❌ Code format, Chinese character or header check failed!"
        echo ""
        echo "For format issues, run this command locally:"
        echo "clang-format -style=file -i [modified files]"
        echo ""
        echo "For Chinese characters, manually remove all Chinese text/comments."
        echo "Chinese characters are not allowed in the codebase."
        echo ""
        echo "For header issues, ensure each file has:"
        echo "- /** comment block with @file, @brief, @copyright tags"
        echo "- Copyright year ending with current year"
        echo "- Modification history is optional but recommended"
        echo ""
        echo "Or use the project's pre-commit hook for automatic formatting:"
        echo "cp tools/hooks/pre-commit .git/hooks/"
        echo "chmod +x .git/hooks/pre-commit" 